//
// Created by Cédric Leclercq on 18/11/2021.
//

#ifndef ADVANCEDPROGRAMMINGDOODLEJUMP_PLATFORM_H
#define ADVANCEDPROGRAMMINGDOODLEJUMP_PLATFORM_H


class Platform {

};


#endif //ADVANCEDPROGRAMMINGDOODLEJUMP_PLATFORM_H
