//
// Created by Cédric Leclercq on 18/11/2021.
//

#ifndef ADVANCEDPROGRAMMINGDOODLEJUMP_PLAYER_H
#define ADVANCEDPROGRAMMINGDOODLEJUMP_PLAYER_H


class Player {

};


#endif //ADVANCEDPROGRAMMINGDOODLEJUMP_PLAYER_H
