//
// Created by Cédric Leclercq on 26/12/2021.
//

#ifndef ADVANCEDPROGRAMMINGDOODLEJUMP_OBSERVER_H
#define ADVANCEDPROGRAMMINGDOODLEJUMP_OBSERVER_H


class Observer {

};


#endif //ADVANCEDPROGRAMMINGDOODLEJUMP_OBSERVER_H
